apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-worker-lbtest
  labels:
    name: locust-lbtest
    role: worker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: locust-lbtest
        role: worker
    spec:
      containers:
        - name: locust-lbtest
          image: pbrumblay/locust-lbtest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master-lbtest
            - name: TARGET_HOST # not needed if you specify full urls in your tests
              value: http://this.is.ignored.com
            - name: NOSSLURL
              value: http://<IP OF NLB WITHOUT SSL ENDPOINT>/ssl/nosslno
            - name: SIDECARURL
              value: https://<IP OF NLB WITH SSL SIDECAR>/ssl/sidecar
            - name: HTTPSLBURL
              value: https://<IP OF HTTPSLB ENDPOINT (FROM INGRESS)>/ssl/httpslb
